#!/bin/zsh

quiet stopwatch
debug ZPLUGINRC

#
# Zplugin configuration
#

source $HOME/.zen/zplugin/git

zplugin cdclear -q # <- forget completions provided up to this moment

source $HOME/.zen/zplugin/prompt
source $HOME/.zen/zplugin/history
source $HOME/.zen/zplugin/plugins


debug_loadtime ZPLUGINRC
