#!/bin/zsh

quiet stopwatch
debug ZPREZTORC


#
# Prezto rc
#
require "${ZDOTDIR:-$HOME}"/.zen/lib/zprezto/runcoms/zpreztorc

# Set the Prezto modules to load (browse modules).
# The order matters.
zstyle ':prezto:load' pmodule \
  'completion' \
  'directory' \
  'editor' \
  'environment' \
  'git' \
  'haskell' \
  'history' \
  'history-substring-search' \
  'homebrew' \
  'node' \
  'osx' \
  'prompt' \
  'python' \
  'rails' \
  'rsync' \
  'ruby' \
  'spectrum' \
  'syntax-highlighting' \
  'terminal' \
  'tmux' \
  'utility'

debug_loadtime ZPREZTORC
