#!/bin/zsh

quiet stopwatch
debug ZPROFILE

#
# Text editing - override these in ~/.zprofile.local if needed
#
export EDITOR='emacs -nw'
export ALTERNATE_EDITOR='emacs'
export VISUAL='emacs'

export NNTPSERVER='news.inet.fi'
export PAGER='less'

export TZ='Europe/Helsinki'

# export INPUTRC="${ZDOTDIR:-$HOME}/.inputrc"
#[[ $TERM = "xterm" ]] && stty -parenb -istrip cs8

#
# Paths
#
typeset -gU path
path=(
    ${ZDOTDIR:-$HOME}/bin
    /usr/local/{bin,sbin}
    /opt/local/bin  # Manually installed software
    $path
)
export PATH

#
# Local zprofile
#
require "${ZDOTDIR:-$HOME}"/.zprofile.local


debug_loadtime ZPROFILE
