#!/usr/bin/env zsh
#
# ZPROFILE - run once on login shells
#

quiet stopwatch
debug ZPROFILE

#
# Text editing - override these in ~/.zprofile.local if needed
#
export CHARSET='UTF-8'
export DISPLAY=':0.0'

alias emacs-daemon-p='ps -xe -o args | grep -s "^emacs --daemon"'
if ! $(emacs-daemon-p -q); then
    emacs --daemon
else
    echo "Emacs server is running"
fi

if [[ -z "${EDITOR}" ]] ; then
    export ALTERNATE_EDITOR='emq'
    export EDITOR='emacsclient'
fi
if [[ -n "${EDITOR}" && -z "${VISUAL}" ]] ; then
  export VISUAL="${EDITOR}"
  # export VISUAL='st -f monospace-12 emacs -nw -q'
fi
export PAGER='less -F'

export NNTPSERVER='news.inet.fi'
export TZ='Europe/Helsinki'

# export INPUTRC="${ZDOTDIR:-$HOME}/.inputrc"
#[[ $TERM = "xterm" ]] && stty -parenb -istrip cs8

#
# Paths
#
typeset -gU path
path=(
    ${ZDOTDIR:-$HOME}/bin
    /opt/local/bin  # Macports or manually installed
    /usr/local/{bin,sbin}
    $path
)
export PATH

#
# Zen garden
#
require "${ZDOTDIR:-$HOME}"/.zen/garden/functions

# Do only when not in an SSH session
if [[ -z $SSH_CLIENT ]]
then
    gpg-agent-start
    ssh-agent-start
fi

#
# Local zprofile
#
require "${ZDOTDIR:-$HOME}"/.zprofile.local

debug_loadtime ZPROFILE
debug
