#!/bin/zsh

quiet stopwatch
debug ZPROFILE

#
# Prezto zprofile
#
require "${ZDOTDIR:-$HOME}"/.zen/lib/zprezto/runcoms/zprofile

#
# Text editing - override these in ~/.zprofile.local if needed
#
export LC_CTYPE='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

export CHARSET='UTF-8'
export DISPLAY=':0.0'

export EDITOR='emacs -nw'
export VISUAL='emacs'
export ALTERNATE_EDITOR='emacs'
export PAGER='less'
# export INPUTRC="${ZDOTDIR:-$HOME}/.inputrc"

export NNTPSERVER='news.newshosting.com'
export TZ='Europe/Berlin'

#
# Paths
#
typeset -gU path
path=(
    ${ZDOTDIR:-$HOME}/bin
    /usr/local/{bin,sbin}
    $path
    ./node_modules/.bin
)
export PATH

#
# Local zprofile
#
require "${ZDOTDIR:-$HOME}"/.zprofile.local


debug_loadtime ZPROFILE
