#!/bin/zsh

#
# Init zshenv
#

# ZSH startup debugging, uncomment next line to enable
# ZSH_DEBUG=1
export ZSH_DEBUG=${ZSH_DEBUG:-0}

# Zsh tools
. ~/.zen/garden/tools

quiet stopwatch
debug "ZSHENV"

#
# Environment - override these in ~/.zshenv.local if needed
#
export CHARSET='UTF-8'
export DISPLAY=':0.0'
export LC_ALL='en_US.UTF-8'
export LC_CTYPE='en_US.UTF-8'
export RSYNC_RSH='ssh'
export TZ='Europe/Helsinki'

#
# Local zshenv
#
require "${ZDOTDIR:-$HOME}"/.zshenv.local


debug_loadtime ZSHENV
debug
