#!/usr/bin/env zsh

quiet stopwatch
debug ZSHRC


#
# Zplugin
#
# require "${ZDOTDIR:-$HOME}"/.zplugin/bin/zplugin.zsh
# autoload -Uz _zplugin
# (( ${+_comps} )) && _comps[zplugin]=_zplugin
# require "${ZDOTDIR:-$HOME}"/.zen/rc/zpluginrc

#
# Command history
# http://zsh.sourceforge.net/Doc/Release/Options.html#History
#
export HISTFILE=~/.zsh_history
export HISTSIZE=10000
export SAVEHIST=50000

# Ignore duplicates commands in the historylog
#
# ignorespace	| don't save lines which begin with a <space> character
# ignoredups	| don't save lines matching the previous history entry
# ignoreboth	| use both 'ignorespace' and 'ignoredups'
# erasedups	  | eliminate duplicates across the whole history
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+:}ignoreboth

# Make some commands not show up in history
export HISTIGNORE=${HISTIGNORE:-"shutdown*:halt*:poweroff*:rm -rf*"}

# Add the date to the historylog
export HISTTIMEFORMAT=${HISTTIMEFORMAT:-"%Y-%m-%d %H:%M:%S"}

#
# Options
#
setopt append_history
setopt auto_cd
setopt auto_menu
setopt auto_pushd
setopt chase_dots
setopt hist_expire_dups_first
setopt hist_find_no_dups
setopt hist_no_functions
setopt hist_reduce_blanks
setopt notify
unsetopt beep
#unsetopt correct_all

#
# Key bindings
#
bindkey -e

# History search keys
bindkey "^[[1;5A" history-incremental-pattern-search-backward  # C-Up
bindkey "^[[1;5B" history-incremental-pattern-search-forward  # C-Down

#
# Load ZSH modules
#

#
# Autoloads
#

autoload -Uz compinit
compinit -i

autoload -U colors
colors

# Prompt
autoload -U promptinit
promptinit
if test 'root' = $(whoami); then
    prompt fade red
else
    prompt fade blue
fi

# Zsh builtin modules
autoload -U zmv

#
# Zen garden
#
require "${ZDOTDIR:-$HOME}"/.zen/garden/aliases
require "${ZDOTDIR:-$HOME}"/.zen/garden/utils

#
# Local zshrc
#
require "${ZDOTDIR:-$HOME}"/.zshrc.local


debug_loadtime ZSHRC
debug
