#!/bin/zsh

quiet stopwatch
debug ZSHRC


#
# Zplugin
#
require "${ZDOTDIR:-$HOME}"/.zplugin/bin/zplugin.zsh
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin
require "${ZDOTDIR:-$HOME}"/.zen/rc/zpluginrc

#
# Command history
#
export HISTFILE=~/.zsh_history
export HISTSIZE=${HISTSIZE:-100000}
export SAVEHIST=50000

# Ignore duplicates commands in the historylog
#
# ignorespace	| don't save lines which begin with a <space> character
# ignoredups	| don't save lines matching the previous history entry
# ignoreboth	| use both 'ignorespace' and 'ignoredups'
# erasedups	  | eliminate duplicates across the whole history
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+:}erasedups

# Make some commands not show up in history
export HISTIGNORE=${HISTIGNORE:-"shutdown*:halt*:poweroff*:rm -rf*"}

# Add the date to the historylog
export HISTTIMEFORMAT=${HISTTIMEFORMAT:-"%Y-%m-%d %H:%M:%S"}

#
# Options
#
bindkey -e
setopt appendhistory autocd notify
unsetopt beep
unsetopt correct_all
#[[ $TERM = "xterm" ]] && stty -parenb -istrip cs8

# Completion
autoload -Uz compinit
compinit -i

# Shell colors
autoload -U colors
colors

# Prompt
autoload -U promptinit
promptinit
# prompt cloud '✯'
# prompt cloud '*'
prompt fade magenta white black

# Zsh builtin modules
autoload -U zmv

# Aliases
require "${ZDOTDIR:-$HOME}"/.zen/garden/aliases

# Zen utils
require "${ZDOTDIR:-$HOME}"/.zen/garden/utils

#
# Local zshrc
#
require "${ZDOTDIR:-$HOME}"/.zshrc.local


debug_loadtime ZSHRC
