#!/bin/zsh

#
# Shell utils
#

# Basic commands
alias rm='nocorrect rm'
alias ls='ls -Gh'
alias l='ls -l'
alias ll='ls -la'
alias lsd='ls -ld'

# Search is like ag/ack:
alias search='grep -r --exclude-dir=.git --exclude-dir=_darcs --exclude-dir=.bzr --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=vendor $1'

# Find largest/smallest files in a directory
alias biggest_files='gfind -type f -printf "%s %p\n" | sort -nr | head'
alias smallest_files='gfind -type f -printf "%s %p\n" | sort -n | head'

alias ltail='less -Ri +F'
alias paths="echo $PATH | perl -pe 's/:/\n/g'"
alias stdout='$1 2>&1'  # Combine stderr to stdout
alias zargs='tr "\n" "\0" | xargs -0'

# Processes
alias agents='launchctl list | cut -f3 | grep -v Label | sort -u'
alias cpu='ps -vxamrhw | more -EwSq~'
alias mem='ps -xavh | more -EwSq~'
alias mysqld_kill='ps aux | grep mysqld | grep -v grep | tabify | cut -f 2 | sudo xargs kill'
alias psc='ps -ar $*| less'
alias psm='ps -xamv $* | less'
alias psr='ps -xvmr $* | less'
alias pss='ps aux | tr "\n" "\0" | xargs -0 -n1 echo | grep -i $1'
alias zombies='ps -Av | grep " Z " | grep -v grep'

#
# Text utils
#

# Logs: tail recent log files which names match a grep argument.
# Example: logs -P '(apa|error|sys)' | prism -m
logs() {
    find {/usr/local,/sw,}/var/log{/apache2,} -atime -3 -type file -and -name '*[._]log' -print0 2>/dev/null | \
        grep -zZ $* | \
        sort -zu | \
        xargs -0 tail -f
}

replace () {
    perl -pe "s/$(echo $1)/$(echo $2)/g"
}
alias tabify="replace ' +' '\t'"
alias untabify="replace '\t' '    '"
alias quotelines="replace '^(.*)\n' '\"\1\"\n'"

#
# Programming
#

alias todo='search -E "((//|#|--)\s+(TODO|REMOVEME|FIXME))"'
alias svn-commits-for-merge="cut -d'|' -f1 | sort -u | perl -pe 's/ *r([0-9a-f]+) *\n/\1,/g'"

# Git
function git-base-diff () {
    git merge-base "$1" `git rev-parse --abbrev-ref HEAD 2>/dev/null`
}

alias gam="gss | grep '^.M' | cut -c4- | cut -d' ' -f3 | xargs git add"
alias git-assume="git update-index --assume-unchanged '$@'"
alias git-unassume="git update-index --no-assume-unchanged '$@'"
alias git-assumed="git ls-files -v | grep ^h | cut -c 3-"
alias gbm='git diff `git-base-diff test-coverage`'
alias git-open-new="gss | grep -E '^??' | tabify | cut -f2 | xargs open"

# Emacsclient
alias emx-start="emacsclient -e '(server-start)'"
alias emx-kill="emacsclient -e '(server-shutdown)'"
alias em="emacsclient -t"
alias emx="emacsclient -c -n -a emacs"  # Open an Emacs editor with GUI

# Readline rlwrap
# alias node="env NODE_NO_READLINE=1 rlwrap node"
alias sbcl="rlwrap sbcl"
alias ccl="rlwrap ccl"
alias ccl64="rlwrap ccl64"


# Utils

about() {
    # Grep manpages by sections
    local cmd=$1; shift
    man $cmd | grep_sections $* | doublelines
}

striplines () { ruby -ne 'puts $_.strip' }
removehyphens () { perl -pe 's/-$//' }
doublelines () { perl -pe 's/\n/\n\n/' }

null_separate_sections () {
    # Read whole input at once with -0777
    ruby -0777 -pe 'gsub(/\n\n/, "\0")' | perl -pe 's/\n/ /'
}

grep_sections() {
    # Grep input by sections (separated by two newlines)
    grep -B8 -A24 $* | striplines | removehyphens | null_separate_sections | \
	xargs -0 -n1 echo | \
	grep $*
}


# Python

if alias ipython; then
    unalias ipython
fi
# Make IPython use virtualenv Python instead of the system Python
alias ipython="python `whence ipython` --pprint"


# Haskell

alias cabal-install-qt="cabal install $1 --ghc-options='-framework-path=$QT_DIR/lib'"
alias cabal-installed-pkgs="ghc-pkg --simple-output list | ruby -pe 'gsub(/ /, \"\n\")' | ruby -pe 'gsub(/-[\d\.]+$/, \"\")' | sort -u"
alias cabal-license="grep -E '(^\* |License:)' | ruby -pe 'gsub(/\s+\([^)]+\)\s+/, \"\")' | ruby -pe 'gsub(/(^\* |\s+License)/, \"\")'"
alias cabal-all-licenses="cabal-installed-pkgs | xargs cabal info | cabal-license"


# Ruby

alias rb='rbenv'
alias be='bundle exec'

# Abbreviation for "gem install".
gi() {
    gem install $@
    rbenv rehash
    rehash
}


#
# Databases
#

# Rexster
alias rex="rexster.sh"
alias rexcon="rexster-console.sh"

# PostgreSQL
alias pg="sudo -u postgres pg_ctl $1 -D $PGDATA -l $PGDATA/pgsql.log"
# alias postgres_server_start='sudo -u postgres postgres -D /opt/local/var/db/postgresql91/defaultdb &'

# MySQL
# alias mysqld_start='sudo mysqld_safe --defaults-file=/opt/local/etc/mysql55/my.cnf --socket=/opt/local/var/run/mysql55/mysqld.sock --user=_mysql &'


#
# Mac OS X specific aliases
#
if os_type 'Darwin'; then
    require "${ZDOTDIR:-$HOME}"/.zen/garden/aliases_osx
fi

#
# Local aliases
#

require "${ZDOTDIR:-$HOME}"/.aliases.local
