#!/usr/bin/env zsh

quiet stopwatch
debug FUNCTIONS


#
# GPG
#
gpg-agent-start () {
    if not_running gpg-agent ; then
        echo "Summoning GPG agent"
        eval $(gpg-agent --daemon -q)
        export GPG_TTY=$(tty)
        export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
    else
        debug "GPG agent is crypting"
        eval $(gpg-connect-agent --quiet /bye)
    fi
}

#
# SSH
#
ssh-agent-start () {
    if not_running ssh-agent ; then
        echo -n "Hello from SSH "
        eval $(ssh-agent -s)
    else
        debug "SSH agent is running"
    fi
}


#
# Python and virtualenvs
#

# Replace 669kb of scripts on pyenv virtualenvwrapper:
workon () {
    source "$HOME/.pyenv/versions/$1/bin/activate"
}


venv () {
    source "./venv/$1/bin/activate"
}

debug_loadtime FUNCTIONS
