#!/bin/zsh

quiet stopwatch
debug UTILS


#
# Zsh libraries
#

# Z from rupa/z
require "${ZDOTDIR:-$HOME}/.zen/lib/rupa/z/z.sh"

# Pip
require "${ZDOTDIR:-$HOME}/.zen/lib/pip_completion"

# Oh my Zsh plugins
require "${ZDOTDIR:-$HOME}/.zen/lib/tevren/git-zsh-plugin/git.plugin.zsh"


#
# Package managers
#

# Fink
require '/sw/bin/init.sh'

# Nix
# require "${ZDOTDIR:-$HOME}/.nix-profile/etc/profile.d/nix.sh"

# Opam (OCaml packages)
require "${ZDOTDIR:-$HOME}/.opam/opam-init/init.zsh"


#
# Shells
#

## Xiki shell
require "${ZDOTDIR:-$HOME}/.xsh"


debug_loadtime UTILS
